export const CREATE_TODO = "CREATE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const RETRIEVE_TODOS = "RETRIEVE_TODOS";
export const DELETE_TODO = "DELETE_TODO";
export const RETRIEVE_SELECTED = "RETRIEVE_SELECTED";
